### ISSUE TITLE
Some images missing

### ISSUE THREAD

**Issue by StuartHarris** [redbadger/blog-squarespace-template#25]
I haven't had a chance to check through all my posts, but this one has images missing...
https://red-badger.com/blog/2015/04/27/tech-round-table-2015
Thanks :-)

**Comment by asavin** [comment]
https://web.archive.org/web/20160418090641/http://red-badger.com/blog/2015/04/27/tech-round-table-2015/

@StuartHarris can you point out what images are missing?
